### ISSUE TITLE
Add DDS 5.2 Libraries

### ISSUE THREAD

**Issue by nknotts** [rticommunity/rticonnextdds-connector#22]
We are beginning our migration to 5.2 and use the node.js bindings. I know I can use the compatibility mode with my 5.2 applications but would prefer not to.

**Comment by gianpiero** [comment]
Hello @nknotts,

I just updated the libraries for the connector: they are now compiled against 5.2.0. Please let me know if you have any issue. 

Regards,
 Gianpiero
