### ISSUE TITLE
Access complex struct

### ISSUE THREAD

**Issue by SMONTA** [rticommunity/rticonnextdds-connector#33]
Hello,
I would to know if the rticonnextdds-connector.py and the library available in lib directory are specific to an example “is this case the ShapeExample application” or it can be used as generic lib for other applications even when complex types exist like modules.
For example if I have this type defintion:

```
<module name="AAA">
        <module name="BBB">
          <module name="CCC">
            <struct name= "ElementId" >
              <member name="id" type="string"/>
              <member name="name" type="string"/>
            </struct>
          </module>
        </module>
      </module>
```

How can I set/read elements under ElementId?
Thank you in advance.

**Comment by gianpiero** [comment]
Hello @SMONTA,

The connector is *NOT* specific to the example: it is a generic api and you can use it with any type! 

If your type is the following:

```
    <types>

        <module name="AAA">
        <module name="BBB">
          <module name="CCC">
            <struct name= "ElementId" >
              <member name="id" type="string"/>
              <member name="name" type="string"/>
            </struct>
          </module>
        </module>
      </module>

      <struct name="ShapeType" extensibility="extensible">
            <member name="elementId" type="nonBasic" nonBasicTypeName="AAA::BBB::CCC::ElementId"/>
        </struct>

    </types>
```

you can set the fields of ElementId in this way:

```
...
for i in range(1,500):
	output.instance.setNumber("elementId.id", i);
	output.instance.setString("elementId.name", "name-"+ str(i));
	output.write();
	time.sleep(2)
...
```

Please find the Example.xml file i used to reproduce your use case and the writerE.py and readerE.py in this [gist](https://gist.github.com/gianpiero/12bef513cfce837dca7b8aa7b98db4c4)

Let me know if this works for you.

Best,
  Gianpiero

**Comment by SMONTA** [comment]
Hello @gianpiero,
 
This is what i expect. It works fine.

Best Regards
Saber
