### ISSUE TITLE
Instantiate Connector object

### ISSUE THREAD

**Issue by SMONTA** [rticommunity/rticonnextdds-connector#34]
Hello, 

I want to define 2 instances of the object connector with different configuration so I define  two xml configuration files in each one I define QoS, Domaine, Topic…
Then in the instantiation of Connector object I do:
connector = rti.Connector("MyParticipantLibrary::domain_participant1",filepath_to_config_file1);
connector1 = rti.Connector("MyParticipantLibrary::domain_participant2",filepath_to_config_file1);

but I get an error in the instantiation of second object:
“
DDS_PropertyQosPolicyHelper_add_property:!new property. PROPERTY ALREADY EXISTS. EITHER REMOVE THIS CALL OR CALL assert_property INSTEAD.
RTI Connector Unable to access RTI Data Distribution Service Core Libraries
See www.rti.com for more information.
RTIDDSConnector_newI:!new unable to add license
RTIDDSConnector_EntitiesLookupList_delete:RTIDDSConnector
“
Can you tell me what's the wrong and what's limitation with RTI DDS conencor?
Thanks in advance.

**Comment by gianpiero** [comment]
Hello @SMONTA,

I am not sure why is not working for you. I am running an example on my mac using the connector for nodejs. I am using the following example (xml and js file [here](https://gist.github.com/gianpiero/ba1dcee9564ffcb6b5810c9843ccf75a)) with two connectors created in the same file and it seems to work fine:

```
$ node simple/writer.js
Writing...
Writing 1...
Writing...
Writing 1..
```

Please have a look to the example linked above and let me know if you still run into the issue. If yes, can you share a reproducer?

Best,
  Gianpiero
