### ISSUE TITLE
windows 64 bit not enabled

### ISSUE THREAD

**Issue by wengjjpaul** [rticommunity/rticonnextdds-connector#35]
rticonnextdds_connector.py is missing the 64 bit windows check. I needed to modify to include a check for 64 bit to use the right rti_dds_connector.dll for it to work on my 64 bit windows.

**Comment by gianpiero** [comment]
Hello @wengjjpaul , 

Thanks for pointing that out. I added support for it. you can see the changes in [this](https://github.com/rticommunity/rticonnextdds-connector/commit/719c0d5efd7a53bb65891b1eac563786a8e3b28f) commit.

I'll close he issue. Let me know if you have any issues.

Best,
  Gianpiero
