### ISSUE TITLE
Exposing Reader/Writer Listener Callbacks for python

### ISSUE THREAD

**Issue by sid5291** [rticommunity/rticonnextdds-connector#41]
Hi,

I was wondering if it would be possible to  expose the Reader/Writer Listener Callbacks for the python dds connector API.

I am specifically looking to expose the following function calls to your rticonnextdds-connector library:

RTIDDSConnectorReadersListener_on_liveliness_changed
RTIDDSConnectorReadersListener_on_requested_deadline_missed
RTIDDSConnectorReadersListener_on_requested_incompatible_qos
RTIDDSConnectorReadersListener_on_sample_rejected

RTIDDSConnectorWriterListener_on_liveliness_lost
RTIDDSConnectorWriterListener_on_offered_deadline_missed
RTIDDSConnectorWriterListener_on_offereded_incompatible_qos

If you have the interface to these calls defined/documented I could then also write a small patch for myself.

Thank You

**Comment by gianpiero** [comment]
Hello @sid5291, 

The Connector scope is limited. As you can see we are exposing a simplified model compared to the full DDS model. With the connector we were not trying to do a full DDS binding but just a component for quick prototyping. That also has the advantage of being more 'maintainable'. 

But I understand that from some users those functionality can be useful. What I had in mind was to add a couple of method to the connector API that will allow the user to retrieve the original c pointer to the entity (for example an output port could have a getNativeWriter() function to get the original c pointer to the writer) and then let advanced user like you to call any DDS api they want (for example the listeners)

In that way we achieve the original goal of simplicity and maintainability of the connector project, adding a bit of flexibility for advanced use cases

Does this make sense? Would that functionality be enough for your use case? 

Best,
  Gianpiero

**Comment by sid5291** [comment]
Hi @gianpiero,

That actually sounds perfect for my use case.  I think that solution would work the best. Thank you. 

Also just to get an idea as I am working on a time sensitive project, do you have an estimate on when you will be incorporating these changes ?

Thanks.

**Comment by gianpiero** [comment]
Hello @sid5291 ,

Unfortunately I don't have a timeline for you. Would it be possible to you to contact support@rti.com and request this feature (add the link to this ticket). That will help to bump this up. 

Best,
  Gianpiero

**Comment by sid5291** [comment]
@gianpiero ,
Thanks I will put in a request for this feature add.
Thank you.
