### ISSUE TITLE
Memory Leak when using dictionary

### ISSUE THREAD

**Issue by wengjjpaul** [rticommunity/rticonnextdds-connector#42]
I encounter memory leak when using samples.getDictionary(j) for data with large sequences of numbers. Any idea?

**Comment by gianpiero** [comment]
Hello,

could u provide a simple reproducer so i can instrument and check where the leak is coming from?

Best

**Comment by gianpiero** [comment]
I am closing this because I was not able to reproduce it. If you can provide a reproducer,  feel free to reopen it.

Thanks

**Comment by gianpiero** [comment]
Hello,

We were able to reproduce the issue. Please follow developments in #53
