### ISSUE TITLE
Sequence not resizing to smaller array using setFromJSON

### ISSUE THREAD

**Issue by rmdabell** [rticommunity/rticonnextdds-connector#43]
I have seen an issue when writing a Sequence using the JavaScript connector through Node.js on a x64Windows. 

My IDL has a Sequence with a complex data type and I use setFromJSON with a JSON object to fill out the writer instance. If I set the sequence with x number of values then write it works great. Any subsequent calls to setFromJSON with an array of values less than x doesn't shrink the Sequence to the new number of values, it stays at x number of values. I've noticed that there is a clear function implemented in the rti_dds_connector.dll and with that function I cleared the value before writing which worked to resize the Sequence (or more accurately, reinitialize the Sequence). 

Should an array of smaller size cause a Sequence to resize to the new smaller size or should I need to somehow call clear on the writer instance to reset the Sequence to the new size?

**Comment by gianpiero** [comment]
Hello @rmdabell ,

You are right: the way to resize the sequences is to call clear on the writer instance. 

Best,
  Gianpiero

**Comment by rmdabell** [comment]
The clear function is implemented in the native code but the method is not in the JavaScript interface.  I had to manually add for testing but I much rather get official version.  The changed rticonnextdds-connector.js file is attached.

[rticonnextdds-connector.js.txt](https://github.com/rticommunity/rticonnextdds-connector/files/911116/rticonnextdds-connector.js.txt)

**Comment by gianpiero** [comment]
Thanks @rmdabell ,

but i think the function clear_member [[here](https://github.com/rticommunity/rticonnextdds-connector/blob/master/rticonnextdds-connector.js#L181)] on the output (writer) was added in august 2016. I think that should do the job.

There is an example on how to use it [here](https://github.com/rticommunity/rticonnextdds-connector/blob/master/examples/nodejs/simple/writer.js#L19)

Let me know,
 Best

**Comment by rmdabell** [comment]
Ah, yes.  I was using version 0.1.8. Thanks for your help.
