### ISSUE TITLE
Adding arm v8 support

### ISSUE THREAD

**Issue by KastanDay** [rticommunity/rticonnextdds-connector#48]
We're trying to use this DDS on the Nvidia Jetson TX2, a 64-bit Arm v8 chip.  Would you consider adding support for this popular board?  It was perfect on the TX1 (32-bit), but we can't pass up the new hardware.  Thank you. -Kastan Day

**Comment by gianpiero** [comment]
Hello Kastan Day, 

Are you looking for the full RTI Connext DDS API or for the connector? In either case I'd suggest you contact support@rti.com to request a specific platform.

Best,
  Gianpiero
