### ISSUE TITLE
There seems no error handling for setFromJSON() for the Node connector version

### ISSUE THREAD

**Issue by shiwanlin** [rticommunity/rticonnextdds-connector#51]
There seems no error handling for 
  this.setFromJSON = function(jsonObj) {
    rtin.RTIDDSConnector_setJSONInstance(output.connector.native,output.name, JSON.stringify(jsonObj));
  }
It does not return error code and does not throw an exception for a certain error but just printing out some console message, something like this:

RTILuaJsonHelper_parse_json_node:!get kind failed for 'deviceId'

(This is for the case the JSON object passed does not contain a required/expected field.)

Of course, one can argue that the app needs to validate the JSON object before passing it in. However, there could be other types of the error within the connector codes an app developer may not anticipate. Production software needs better error handling than just console printing out... :-)

**Comment by gianpiero** [comment]
Hello,

Thanks for your feedback. We are aware of some functions that do not report errors, for example the write operation is another one beside the setFromJSON. 

The Connector is an internal tool that we develop to put together quick demo and tests in the RTI Research Team. We decided to share it to gather early feedback, but we clearly state in the main README [here](https://github.com/rticommunity/rticonnextdds-connector#support), that is an '**experimental**' product and we don't officially support it (beside on the community forum).

We agree with you: Better error handling is necessary for production software! Unfortunately connector is not there yet. We are working on improving it and we really appreciate you trying this out and providing your feedback.

You can contact your local sales rep (sales@rti.com) to learn more about roadmap and timeline.  

Thank you,
  Gianpiero
