### ISSUE TITLE
Is it possible to set outpot to a serialized value instead of the setNumber for each.

### ISSUE THREAD

**Issue by itayo** [rticommunity/rticonnextdds-connector#56]
I have data in serialized way and would like to set this directly instead of setting each field.

Is this possible with rticonnextdds-connector or do i have to go for each field?

**Comment by gianpiero** [comment]
Hello, 

Unfortunately we do not have that capability in connector. The only thing you can do is to create a object (nodejs) or a dictionary (python) that describes the whole sample and then call 
_**setFromJSON**_ (nodejs) or _**setDictionary**_ (python) to set it all at once.

I hope this help. 

Best,
  Gianpiero

**Comment by itayo** [comment]
@gianpiero  thank you for information
