### ISSUE TITLE
Potential Memory Leak in Javascript Connector

### ISSUE THREAD

**Issue by nnash** [rticommunity/rticonnextdds-connector#57]
Setup:
Node js app that sends DDS messages as well as another Node js app that is listening.

It grows steadily and I have narrowed the leak down to either the rti connector or Node. To track the memory usage I use top on Linux. 

[qos.txt](https://github.com/rticommunity/rticonnextdds-connector/files/1519454/qos.txt)
Node version 6.10.3

Can you help me out?

**Comment by gianpiero** [comment]
Hello nnash,

We identify the same issue in python (#53) and fixed it with a workaround for python only. We filed an internal bug  (CON-49)  and we want to fixe the issue in a more efficient one that loans the string to the scripting layer and then the scripting layer will return the loan, but the work hasn't been scheduled yet.

If this is urgent for you I would suggest you'll contact your local sales manager.

Regards,
  Gianpiero

**Comment by nnash** [comment]
Thanks gianpiero. I figured that this would be the case, but was hoping that only effected the python implementation.
