### ISSUE TITLE
How to specify the qos of a topic with xml

### ISSUE THREAD

**Issue by shixukai** [rticommunity/rticonnextdds-connector#62]
I have the xml config as this:
```  
<qos_library name="QosLibrary">
    <qos_profile name="DefaultProfile" base_name="BuiltinQosLibExp::Generic.BestEffort" is_default_qos="true">
      <participant_qos>
        <transport_builtin>
          <mask>UDPV4 | SHMEM</mask>
        </transport_builtin>
      </participant_qos>
    </qos_profile>

    <qos_profile name="ReliableProfile" base_name="BuiltinQosLibExp::Generic.StrictReliable">
      <datawriter_qos topic_filter="ShuttleService*"/>
    </qos_profile>

  </qos_library>
```

```
  <domain_library name="DomainLibraryGroup">
       .....
       <topic name="ShuttleServiceRequest_c0a4c169-05c8-419e-9f5a-653e3a97544a" register_type_ref="ShuttleServiceRequest"/>
       .......
  </domain_library>
```
I hope the datawriter datawriter with prefix ShuttleService work with StrictReliable qos,
But it still  work as BestEffort qos. What I have missed?

**Comment by fabriziobertocci** [comment]
Connector will use the default QoS that in your configuration is currently
set to be the "DefaultProfile".
Remove the attribute

is_default_qos="true"

from the "Default Profile" and place it in the "ReliableProfile"
Then keep in mind that if you still want to keep enabled UDPv4 and Shared
Memory you need to copy those settings as well.

In short, try with this configuration:

<qos_library name="QosLibrary">
    <qos_profile name="ReliableProfile"
base_name="BuiltinQosLibExp::Generic.StrictReliable"
*is_default_qos="true"*>      <participant_qos>
        <transport_builtin>
          <mask>UDPV4 | SHMEM</mask>
        </transport_builtin>
      </participant_qos>
      <datawriter_qos topic_filter="ShuttleService*"/>
    </qos_profile>
</qos_library>



Regards,
Fabrizio

**Comment by shixukai** [comment]
@fabriziobertocci 
thanks for your replay!
If i set the "ReliableProfile" is_default_qos="true",  will this profile affect all topics?
I mean if that will cause all data writer and reader use  "ReliableProfile" as default qos but not only "ShuttleService*"?

**Comment by fabriziobertocci** [comment]
When you define your datawriters (in the domain participant library), you
can to tell each datawriter what is the qos profile to inherit from. For
example:

1. Define two QoS profiles in your QoS library, one for reliable ("
QosLibrary::ReliableProfile") and one for best effort ("
QosLibrary::BestEffortProfile") profile. I.e.:

<qos_library name="*QosLibrary*">
    <qos_profile name="*BestEffortProfile*"
base_name="*BuiltinQosLibExp::Generic.BestEffort*">
      <participant_qos>
        <transport_builtin>
          <mask>UDPV4 | SHMEM</mask>
        </transport_builtin>
      </participant_qos>      <datawriter_qos>
          <history>
            <kind>KEEP_ALL_HISTORY_QOS</kind>
          </history>
        </datawriter_qos>    </qos_profile>

    <qos_profile name="*ReliableProfile*"
base_name="*BuiltinQosLibExp::Generic.StrictReliable*">
      <datawriter_qos topic_filter="ShuttleService*"/>
    </qos_profile>
</qos_library>


2. Then in the domain library, define the two data writers for your
domain participant; for each datawriter specify a custom QoS that
extends one of the QoS defined in the previous QoS library:

    <domain_participant_library name="*MyParticipantLibrary*">
      <domain_participant name="*Zero*" domain_ref="MyDomainLibrary::MyDomain">
        <publisher name="*MyPublisher*">
          <data_writer name="*MyBestEffortWriter*" topic_ref="Square">
            <datawriter_qos base_name="QosLibrary::MyBestEffortProfile">
            </datawriter_qos>
          </data_writer>
          <data_writer name="*MyReliableWriter*" topic_ref="Square">
            <datawriter_qos base_name="QosLibrary::MyReliableProfile">
            </datawriter_qos>
          </data_writer>
        </publisher>
        <subscriber name="MySubscriber">
          <data_reader name="MySquareReader" topic_ref="Square"/>
        </subscriber>
      </domain_participant>
    </domain_participant_library>



3. In your Connector script, just create the Connector object as usual, and
get the writers (example for node.js):
var connector = new
rti.Connector("MyParticipantLibrary::Zero","../ShapesExample.xml");
var output1 = connector.getOutput("MyPublisher::MyBestEffortWriter");
var output2 = connector.getOutput("MyPublisher::MyReliableWriter");


Regards,
Fabrizio
