### ISSUE TITLE
Provide the source to the shared library

### ISSUE THREAD

**Issue by jasontiller** [rticommunity/rticonnextdds-connector#63]
It appears that the connector is essentially unmaintained at this point. Is there any chance that you could add the binary's source? I'd be glad to contribute any enhancements we made, and I'm sure I'm not alone.

Since this tool already has no guaranteed support from RTI, why not make it truly open source?

**Comment by gianpiero** [comment]
Hello @jasontiller,

The Connector was developed under research funding that are no longer available. We then moved it into the RTI Labs "stage" (https://www.rti.com/labs) to gauge interest from potential users an collect feedback. 

The good news is that Connector will be officially supported in the next RTI Connext Release.  

Meanwhile, Connector has been enhanced and bug fixes have been provided for customer that needed a feature acceleration through services contract. If you have such a need you can contact your local RTI representative. 

Best,
  Gianpiero

**Comment by jasontiller** [comment]
OK, so if I understand correctly, there will be an officially supported Connector that will come out... in a year or so... with the next full Connext release. Any idea on the timing for that?

We can pay to have a feature added earlier, if we choose.

Thank you for the update.

**Comment by gianpiero** [comment]
@jasontiller 

If you can/want I'd love to set up a meeting with our PM here to better discuss timing and what's going to be next.

Does it make sense? Can you email me directly gianpiero[at]rti.com?

**Comment by gianpiero** [comment]
I am closing this ticket for now. There is no plan to opensource the connector c library at the moment.
